version: '2.2'
services:
  laravel_nginx:
    image: nginx:1.19.0-alpine
    mem_limit: 512M
    volumes:
      - ./.docker/conf/nginx/templates:/etc/nginx/templates
      - ${LOCAL_PROJECT_PATH}:/var/www/html
    ports:
      - ${LOCAL_NGINX_PORT}:80
#    environment:
#      - NGINX_HOST=${NGINX_HOST}
#      - NGINX_ROOT_DIR=${NGINX_ROOT_DIR}
#      - NGINX_FAST_CGI_PATH=${NGINX_FAST_CGI_PATH}
    depends_on:
      - laravel_php
      - laravel_db
  laravel_php:
    build: .docker
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ${LOCAL_PROJECT_PATH}:/var/www/html
  laravel_db:
    image: postgres:10.14
    mem_limit: 512M
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${LOCAL_POSTGRES_PORT}:5432
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
      - ./.docker/data/pgsql/:/var/lib/postgresql/data/
